apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: kn-create-
spec:
  serviceAccount: kn-deployer-account  # <-- run as the authorized SA

  taskRef:
    name: kn-create
  inputs:
    params:
    - name: service
      value: my-service
    resources:
    - name: image
      resourceSpec:
        type: image
        params:
        - name: url
          value: docker.io/agiertli/knative-hello