apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: telegram-knative-deploy-pipeline
spec:
  resources:
  - name: app-git
    type: git
  - name: app-image
    type: image
  tasks:
  - name: build
    taskRef:
      name: s2i-java-8
    params:
      - name: TLSVERIFY
        value: "false"
    resources:
      inputs:
      - name: source
        resource: app-git
      outputs:
      - name: image
        resource: app-image
  - name: deploy
    taskRef:
      name: kn-create
    resources:
      inputs:
      - name: image
        resource: app-image 
    params:
      - name: service
        value: "knative-telegram-service"